spring.application.name=earthquake-manager

# 1. Database Connection Info
spring.datasource.url=jdbc:postgresql://localhost:5432/earthquake_db
spring.datasource.username=postgres
spring.datasource.password=codeittaskZN9

# 2. Hibernate Magic: Automatically creates the table in Postgres
spring.jpa.hibernate.ddl-auto=update

# 3. Optional: Shows the SQL commands in your console so you can see what's happening
spring.jpa.show-sql=true